#lambda_function_name='superlambda-CreateBatchFunction-FHh7VhqBhB0v',  testing_locally=False, s3_bucket_name='sdl-cifar10'

lambda_function_name: 'superlambda-CreateBatchFunction-FHh7VhqBhB0v'
pre_process_workers: 1
processing_workers: 5 #this must always be at least 2
post_processing_workers: 1

  
testing_locally: False
sam_local_url: 'http://localhost:3000'
sam_local_endpoint: '/create_batch'