s3_data_dir: 's3://sdl-cifar10/train/'
batch_size: 64 #chunk_size  = number of files per chunk
num_pre_cached_batches: 100
drop_last: False
simulate_mode: True
batch_creation_lambda: 'superlambda-CreateBatchFunction-FHh7VhqBhB0v'
pre_process_workers: 1
processing_workers: 5 #this must always be at least 2
post_processing_workers: 1
testing_locally: False
sam_local_url: 'http://localhost:3000'
sam_local_endpoint: '/create_batch'