# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: superdl/syncgrpc/protos/cache_coordinator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/superdl/syncgrpc/protos/cache_coordinator.proto\x1a\x1bgoogle/protobuf/empty.proto\"=\n\x15GetBatchStatusRequest\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\x03\x12\x12\n\ndataset_id\x18\x02 \x01(\t\"N\n\x16GetBatchStatusResponse\x12#\n\x1b\x62\x61tch_cached_or_in_progress\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\x07JoEnded\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\"E\n\x0eJobMetricsInfo\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\x12\x12\n\ndataset_id\x18\x02 \x01(\t\x12\x0f\n\x07metrics\x18\x03 \x01(\t\">\n\x13RegisterJobResponse\x12\x16\n\x0ejob_registered\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"F\n\x17RegisterDatasetResponse\x12\x1a\n\x12\x64\x61taset_registered\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"l\n\x13RegisterDatasetInfo\x12\x12\n\ndataset_id\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61ta_dir\x18\x02 \x01(\t\x12\x15\n\rsource_system\x18\x03 \x01(\t\x12\x18\n\x10labelled_samples\x18\x04 \x01(\t\"6\n\x0fRegisterJobInfo\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x61taset_ids\x18\x02 \x03(\t\"U\n\x16\x42\x61tchAccessPatternList\x12\x0e\n\x06job_id\x18\x01 \x01(\x03\x12\x17\n\x07\x62\x61tches\x18\x02 \x03(\x0b\x32\x06.Batch\x12\x12\n\ndataset_id\x18\x03 \x01(\t\"1\n\x05\x42\x61tch\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\x03\x12\x16\n\x0esample_indices\x18\x02 \x03(\x05\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t2\xde\x02\n\x17\x43\x61\x63heCoordinatorService\x12\x41\n\x0eGetBatchStatus\x12\x16.GetBatchStatusRequest\x1a\x17.GetBatchStatusResponse\x12\x41\n\x0fRegisterDataset\x12\x14.RegisterDatasetInfo\x1a\x18.RegisterDatasetResponse\x12\x35\n\x0bRegisterJob\x12\x10.RegisterJobInfo\x1a\x14.RegisterJobResponse\x12J\n\x17ShareBatchAccessPattern\x12\x17.BatchAccessPatternList\x1a\x16.google.protobuf.Empty\x12:\n\x0fShareJobMetrics\x12\x0f.JobMetricsInfo\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'superdl.syncgrpc.protos.cache_coordinator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETBATCHSTATUSREQUEST']._serialized_start=80
  _globals['_GETBATCHSTATUSREQUEST']._serialized_end=141
  _globals['_GETBATCHSTATUSRESPONSE']._serialized_start=143
  _globals['_GETBATCHSTATUSRESPONSE']._serialized_end=221
  _globals['_JOENDED']._serialized_start=223
  _globals['_JOENDED']._serialized_end=248
  _globals['_JOBMETRICSINFO']._serialized_start=250
  _globals['_JOBMETRICSINFO']._serialized_end=319
  _globals['_REGISTERJOBRESPONSE']._serialized_start=321
  _globals['_REGISTERJOBRESPONSE']._serialized_end=383
  _globals['_REGISTERDATASETRESPONSE']._serialized_start=385
  _globals['_REGISTERDATASETRESPONSE']._serialized_end=455
  _globals['_REGISTERDATASETINFO']._serialized_start=457
  _globals['_REGISTERDATASETINFO']._serialized_end=565
  _globals['_REGISTERJOBINFO']._serialized_start=567
  _globals['_REGISTERJOBINFO']._serialized_end=621
  _globals['_BATCHACCESSPATTERNLIST']._serialized_start=623
  _globals['_BATCHACCESSPATTERNLIST']._serialized_end=708
  _globals['_BATCH']._serialized_start=710
  _globals['_BATCH']._serialized_end=759
  _globals['_MESSAGE']._serialized_start=761
  _globals['_MESSAGE']._serialized_end=787
  _globals['_CACHECOORDINATORSERVICE']._serialized_start=790
  _globals['_CACHECOORDINATORSERVICE']._serialized_end=1140
# @@protoc_insertion_point(module_scope)
