kind: 'langauge'
s3_data_dir: s3://owtchunks/train/ #s3://sdl-cifar10/train/ #s3://imagenet1k-sdl/train/, s3://sdl-cifar10/train/
batch_size: 1 #chunk_size  = number of files per chunk
max_lookahead_batches: 25
max_prefetch_workers: 1
keep_alive_ping_iterval: 900
shuffle: False
drop_last: False
num_dataset_partitions: 1